dbt_youtube:
  outputs:
    dev:
      account: FJEKTWA-HC42026
      database: YOUTUBE_DB
      password: "Aligator@3082002ht"
      role: YOUTUBE_ROLE
      schema: YOUTUBE_DEV_SCHEMA
      threads: 1
      type: snowflake
      user: JIMALAIKA
      warehouse: YOUTUBE_WH
    prod:
      account: FJEKTWA-HC42026
      database: YOUTUBE_DB
      password: "Aligator@3082002ht"
      role: YOUTUBE_ROLE
      schema: YOUTUBE_PROD_SCHEMA
      threads: 1
      type: snowflake
      user: JIMALAIKA
      warehouse: YOUTUBE_WH
  target: dev
